[package]
name = "ordKode"
version = "0.1.0"
edition = "2021"

[dependencies]
gdk4 = { version = "0.9.6", optional = true }
gdk4-sys = { version = "0.9.6", optional = true }
gtk = "0.18.2"

[features]
default = []
gdk4-sys = ["dep:gdk4-sys"]
