name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglib2.0-dev \
          pkg-config \
          libpango1.0-dev \
          gdk-pixbuf-2.0-dev \
          libgtk-4-dev \
          libcairo2-dev \
          libgdk-pixbuf2.0-dev
        sudo apt-get clean

    - name: Debug pkg-config
      run: pkg-config --modversion gtk4

    - name: Build
      env:
        PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
      run: cargo build --verbose

    - name: Run tests
      env:
        PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
      run: cargo test --verbose
