name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libglib2.0-dev \
          pkg-config \
          libpango1.0-dev \
          gdk-pixbuf-2.0-dev \
          libgtk-4-dev \
          libcairo2-dev \
          libgdk-pixbuf2.0-dev \
          libatk1.0-dev \
          libgirepository1.0-dev
        sudo apt-get clean

    - name: Verify GTK4 Installation
      run: dpkg -l | grep gtk

    - name: Debug pkg-config
      run: |
        echo "Checking GTK4 version..."
        pkg-config --modversion gtk4
        echo "Checking GTK4 libraries..."
        pkg-config --libs gtk4

    - name: Capture Detailed Build Logs
      env:
        PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
      run: cargo build --verbose 2>&1 | tee build.log

    - name: Build with Features
      env:
        PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
      run: cargo build --verbose --features "gdk4/gdk4-sys"

    - name: Run tests
      env:
        PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
      run: cargo test --verbose
